<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-RH86VL0" name="Test" tests="7" failures="1" timestamp="12 Mar 2021 11:10:13 GMT" time="0.108" errors="0">
  <testcase name="credential" time="0.018" classname="com.testng.MyTest">
    <skipped/>
  </testcase> <!-- credential -->
  <testcase name="credential" time="0.003" classname="com.testng.MyTest">
    <skipped/>
  </testcase> <!-- credential -->
  <testcase name="credential" time="0.003" classname="com.testng.MyTest">
    <skipped/>
  </testcase> <!-- credential -->
  <testcase name="credential" time="0.002" classname="com.testng.MyTest">
    <skipped/>
  </testcase> <!-- credential -->
  <testcase name="credential" time="0.002" classname="com.testng.MyTest">
    <skipped/>
  </testcase> <!-- credential -->
  <testcase name="credential" time="0.002" classname="com.testng.MyTest">
    <failure type="java.lang.AssertionError" message="expected [kathir] but found [priya]">
      <![CDATA[java.lang.AssertionError: expected [kathir] but found [priya]
	at com.testng.MyTest.credential(MyTest.java:11)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- credential -->
  <testcase name="creditional1" time="0.005" classname="com.testng.MyTest"/>
</testsuite> <!-- Test -->
